---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: list the copied file
      command: "ls -rlt /tmp/script.sh"

    - name: change owner and group of the file
      file: path=/tmp/script.sh owner=ec2-user group=ec2-user mode=0644
